General = {
    {"Chat", title=true},
    {"Enter",                     "Send chat message"},
    {"Alt + Enter",               "Send chat message to allies"},
    {"Shift + Enter",             "Send chat message to spectators"},
    {blankLine=true},    
    {"Menus", title=true},
    {"Shift + Esc",         "Quit menu"},
    {"F11",                 "Widget list"},
    {"Ctrl + F11",          "Widget teak mode"},  
    {"H",                   "Share units / resources"},
    {blankLine=true},
    {"Camera movement", title=true},
    {"scrollwheel",                 "Zoom camera"},
    {"arrow keys / mouse at screen edge", "Move camera"},
    {"Ctrl + scrollwheel",          "Change camera angle"},
    {"middle click (+ drag)",       "Drag camera"},
    {blankLine=true},
    {"Camera modes", title=true},
    {"Ctrl + F1, F2, F3, F4, F5",           "Change camera type"},
    {"Alt + Enter",             "Toggle fullscreen"},
    {"Tab",                         "Toggle overview camera"},
    {"L",   "Toggle LOS view"},
    {"F1",  "Show height map"},
    {"F2",  "Show passability (for selected unit)"},
    {"F3",  "Cycle through map marks"},
    {"F4",  "Show metal map"},
    {"F5",  "Hide GUI"},
    {blankLine=true},
    {"Sound", title=true},
    {"-/+",                 "Change volume"},
    {"F6",                  "Toggle mute"},
}

Units_I_II = {
    {"Selecting units", title=true},           
    {"left mouse (+ drag)",      "Select or deselect units"},
    {blankLine=true},    
    {"Giving orders", title=true},           
    {"right mouse (single click)",   "Give order to unit(s)"},
    {"right mouse (drag)",           "Give formation order to unit(s)"},
    {blankLine=true},    
    {"Selecting orders", title=true},
    {"(none)", "default order (usually move)"},
    {"M",   "move"},
    {"A",   "attack"},
    {"R",   "repair"},
    {"E",   "reclaim"},
    {"F",   "fight"},
    {"P",   "patrol"},
    {"K",   "cloak"},
    {blankLine=true},    
    {"S",   "stop (clears order queue)"},
    {"W",   "wait (pause current command)"},
    {blankLine=true},    
    {"D",   "D-Gun (manual fire weapon)"},
    {"Ctrl + D", "self-destruct"},
    {blankLine=true},    
    {"Giving selected orders", title=true},
    {"left mouse (single click)",    "Give order to unit(s)"},
    {"right mouse (single click)",   "Revert to default order"},
    {"right mouse + drag",           "Give formation order to unit(s)"},
    {blankLine=true},    
    {"Queueing orders", title=true},
    {"Shift + (some order)",         "Add order to end of order queue"},
    {"Space + (some order)",         "Add order to start of order queue"},
}


Units_III = {
    {"Selecting build orders", title=true},
    {"(mouse)",    "Select from units build-menu"},
    {"[ and ], or o",   "Change facing of buildings"},
    {blankLine=true},    
    {"Giving build orders", title=true},
    {"left mouse",   "Give build order"},
    {"right mouse",  "De-select build order"},
    {"Shift + (build order)", "Build in a line"},
    {"Shift + alt + (build order)", "Build in a square"},
    {"Z",           "Increase build spacing"},
    {"X",           "Decrease build spacing"},
    {blankLine=true},    
    {"Group selection", title=true},
    {"Ctrl + A",                "Select all units"},
    {"Ctrl + B",                "Select all constructors"},
    {"Ctrl + (num)",            "Add units to group (num=1,2,..)"},
    {"(num)",                   "Select all units assigned to group (num)"},
    {"Ctrl + Z",                "Select all units of same type as current"},
    {blankLine=true},
    {"Drawing", title=true},
    {"§ + dbl click",       "Place map mark"},
    {"§ + drag left mouse", "Draw on map"},
    {"§ + drag right mouse","Erase drawings and markers"},
    {blankLine=true},
    {"Console commands", title=true},
    {"/clearmapmarks",  "Erase all drawings and markes"},
    {"/clock",          "Toggle ingame clock"},
    {"/fps",            "Toggle ingame fps indicator"},
}
