return {
	zzz_mission_wizzard = {
		acceleration = 12.5,
		maxacc = 12.5,
		airhoverfactor = 0,
		airstrafe = false,
		brakerate = 25.5,
		buildcostenergy = 9096,
		buildcostmetal = 220,
		builddistance = 128,
		builder = true,
		--buildpic = "ARMACA.DDS",
		buildtime = 17763,
		canfly = true,
		cancloak = true,
		canmove = true,
		canpatrol = false,
		canguard = false,
		canfight = false,
		canrepair = false,
		category = "SUB",
		cloakcost = 0,
		cloakcostmoving = 0,
		collide = false,
		cruisealt = 250,
		damagemodifier = 0,
		decloakonfire = false,
		description = "Can build any unit/building",
		energymake = 200000,
		energystorage = 3000000,
		energyuse = 0,
		--explodeas = "CA_EX",
		footprintx = 2,
		footprintz = 2,
		--icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		initcloaked = true,
		maxdamage = 180,
		maxslope = 10,
		maxvelocity = 180.0,
		maxwaterdepth = 0,
		metalmake = 25000,
		metalstorage = 1000000,
		name = "Mission Wizzard",
		objectname = "zzz_mission_wizzard",
		radardistance = 2500,
		script = "zzz_mission_wizzard.cob",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 1500,
		stealth = true,
		--terraformspeed = 650,
		turnrate = 3380,
		workertime = 700000,
		buildoptions = {
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
