local BlackList = {
	["cor_gol"             ] = true,
	["corplas_weapon"      ] = true,
	["corkrog_fire"        ] = true, -- FIXME? should be krogoth_artillery but corkrog_fire has plasma shell CEGs?
--	["krogoth_artillery"   ] = true,
	["commander_self_d"    ] = true,
	["arm_udisintegrator"  ] = true,
	["csarm_disintegrator" ] = true,
	["core_disintegrator"  ] = true,
	["core_udisintegrator" ] = true,
	["cscore_disintegrator"] = true,
	["core_intimidator"    ] = true,
	["cor_bats"            ] = true,
	["armmine5"            ] = true,
	["atomic_blastpen"     ] = true,
	["crblmssl"            ] = true,
	["cortron_weapon"      ] = true,
	["corvipe_laser"       ] = true,
	["corkrog_head"        ] = true,
	["core_artillery"      ] = true,
	["commander_blast"     ] = true,
	["arm_disintegrator"   ] = true,
	["arm_berthacannon"    ] = true,
	["arm_bats"            ] = true,
	["armsnipe_weapon"     ] = true,
	["crawl_blast"         ] = true,
	["atomic_blast"        ] = true,
	["nuclear_missile"     ] = true,
	["armemp_weapon"       ] = true,
	["ARMVULC_WEAPON"      ] = true,
	["FLEAGOTH"            ] = true,
	["Fleagoth_MISSILE"    ] = true,
	["ORCONE_GUN"    	   ] = true,
	["ORCONE_HEAD" 	 	   ] = true,
	["ORCONE_ROCKET"	   ] = true,
	["ORCONE_SHIELD" 	   ] = true,
	["PHASER" 	   		   ] = true,
	["TORPEDO_DISINTEGRATOR"] = true,
	
}


return BlackList