-- a = "b" is the same as "Naughty player you cant build a till youve built b!"
-- XTA 2007
local buildRestrictionDefs = {
    arm_fusion_reactor={"arm_cloakable_fusion_reactor"},
--  core_cloakable_fusion_power_plant={"core_light_fusion_power_plant"},
    core_fusion_power_plant={"core_cloakable_fusion_power_plant"},
    
    arm_adv_aircraft_plant={"arm_kbot_lab",
                      "arm_vehicle_plant",
                      "arm_aircraft_plant",
                      "arm_hovercraft_platform",
                      "arm_seaplane_platform",
                      "arm_shipyard"},
    arm_adv_kbot_lab={"arm_kbot_lab",
                      "arm_vehicle_plant",
                      "arm_aircraft_plant",
                      "arm_hovercraft_platform",
                      "arm_seaplane_platform",
                      "arm_shipyard"},
    arm_adv_shipyard={"arm_kbot_lab",
                      "arm_vehicle_plant",
                      "arm_aircraft_plant",
                      "arm_hovercraft_platform",
                      "arm_seaplane_platform",
                      "arm_shipyard"},
    arm_adv_vehicle_plant={"arm_kbot_lab",
                      "arm_vehicle_plant",
                      "arm_aircraft_plant",
                      "arm_hovercraft_platform",
                      "arm_seaplane_platform",
                      "arm_shipyard"},


-- core factories
    core_adv_aircraft_plant={"core_kbot_lab",
                      "core_vehicle_plant",
                      "core_aircraft_plant",
                      "core_hovercraft_platform",
                      "core_seaplane_platform",
                      "core_shipyard"},
    core_adv_kbot_lab={"core_kbot_lab",
                      "core_vehicle_plant",
                      "core_aircraft_plant",
                      "core_hovercraft_platform",
                      "core_seaplane_platform",
                      "core_shipyard"},
    core_adv_shipyard={"core_kbot_lab",
                      "core_vehicle_plant",
                      "core_aircraft_plant",
                      "core_hovercraft_platform",
                      "core_seaplane_platform",
                      "core_shipyard"},
    core_adv_vehicle_plant={"core_kbot_lab",
                      "core_vehicle_plant",
                      "core_aircraft_plant",
                      "core_hovercraft_platform",
                      "core_seaplane_platform",
                      "core_shipyard"},
                      
    core_krogoth_gantry={
                      "core_adv_aircraft_plant",
                      "core_adv_kbot_lab",
                      "core_adv_shipyard",
                      "core_adv_vehicle_plant"},
}
return buildRestrictionDefs