local tips = {
	'Air repair pad facing controls from where planes will land on it. Don\'t make your planes fly over enemy territory when landing...',
	'Set your factory to guard your commander as last order: that way you will automate your supply line...',
	'Press L to show an unit\'s line of sight',
	'Press Ctrl-E to see how all your energy is spent',
	'Press Ctrl-C to quickly zoom to your commander',
	'Use Ctrl-Z to select all units of same type',
	'Hold Alt or Ctrl-Alt to use the advanced versions of the Guard command',
	'Use T2 bombers to bombard an enemy with a lot of anti-air defences',
	'Don\'t build anti-air defences in your base: build them instead a bit outside. That way they will shoot down bombers before they have released their payload',
	'Use a variety of units to make use of their special attributes and abilities effectively',
	'Don\'t start with building an air or advanced factory, unless you know what you\'re doing',
	'Always remember to scout ahead',
	'The best thing to build after your fusion has been completed is ... another fusion!',
	'Remember the river rule: it\'s cowardous to cross the river into enemy territory with your Commander before 5 minutes into the game',
	'Combombs are totally fine, as long as not done right at the start. Later in the game you should have defences',
	'If unsure what to bomb: go for heavy or normal fusions',
	'Don\'t counter anti-air with air. Use ground forces instead.',
	'Dragon\'s teeth around defensive installations help prolong their life. Use Ctrl-alt-shift to automatically place a box of DT\'s',
	'Cloak and stealth fulfil complimentary functions: cloak prevents visual, while stealth prevents radar detection. Some units can use both at the same time.',
	'Radar jammers will also affect your own radars: disable them if you suspect the enemy has cloaked units inside your base',
	'If you have absolutely no energy: build solars!',
	'If gamemode is commander ends: a last commander who D-Guns the last enemy commander loses, but the one that lasers it to death instead wins.',
	'The supreme art of war is to subdue the enemy without fighting.',
	'Most units can shoot longer than they can see. Use scout units to provide visibility for them.',
	'On metal maps, buildpower is usually the limiting resource. Build constructors.',
	'It only takes one of the second smallest mines to kill a Commander, if he\'s unlucky',
	'If you manage to build a krogoth, protect it (with a lot of spam units) from being D-Gunned',
	'In a King of the Hill (KOTH) game mode, be always aware of the timer',
	'The Commander is visible under water if the enemy has sonar, or if even the smallest piece of his antennae appear above the surface',
	'When units gain experience, they become stronger, faster and more accurate',
	'Use crawling bombs to strike the enemy where he doesn\'t expect it',
	'Do not go gentle into that good night, Old age should burn and rave at close of day; Rage, rage against the dying of the light',
	'Though wise men at their end know dark is right, Because their words had forked no lightning they Do not go gentle into that good night.',
	'Good men, the last wave by, crying how bright Their frail deeds might have danced in a green bay, Rage, rage against the dying of the light.',
	'Wild men who caught and sang the sun in flight, And learn, too late, they grieved it on its way, Do not go gentle into that good night.',
}

return tips